### ISSUE TITLE
AdministrativeUnit GML - One of '{"http://www.opengis.net/gml/3.2":AbstractFeature}' is expected?

### ISSUE THREAD

**Issue by OscarD31** [inspire-eu-validation/ets-repository#103]
Good evening!

I have a GML for the AdministrativeUnits Theme:
[AU.zip](https://github.com/inspire-eu-validation/ets-repository/files/1359934/AU.zip)

I select the 4 tests for the theme Administrative Units and run the validation. Everything is OK, except a schema validation error:

`XML document 'AU.gml': 9:52: cvc-complex-type.2.4.a: Invalid content was found starting with element '{"http://inspire.ec.europa.eu/schemas/au/4.0":AdministrativeUnit}'. One of '{"http://www.opengis.net/gml/3.2":AbstractFeature}' is expected.`

My schema location is as follows:

`xsi:schemaLocation="http://www.opengis.net/wfs/2.0 http://schemas.opengis.net/wfs/2.0/wfs.xsd http://www.opengis.net/gml/3.2 http://schemas.opengis.net/gml/3.2.1/gml.xsd http://inspire.ec.europa.eu/schemas/au/4.0/ http://inspire.ec.europa.eu/schemas/au/4.0/AdministrativeUnits.xsd"`

In the AdministrativeUnits.xsd a substitutionGroup is defined for the AbstractFeature of the gml schema:

`<element name="AdministrativeUnit" substitutionGroup="gml:AbstractFeature" type="au:AdministrativeUnitType">` 

As far as I know, with that code you can use either AbstractFeature or AdministrativeUnit... So, am I missing something in my GML? I think the validator shouldn't give that error.

Besides, I have a GML for the CadastralParcel that I wrote the same way and with that GML I'm not getting that validation error:
[CP.zip](https://github.com/inspire-eu-validation/ets-repository/files/1359971/CP.zip)

Its schemaLocation:

`xsi:schemaLocation="http://www.opengis.net/wfs/2.0 http://schemas.opengis.net/wfs/2.0/wfs.xsd http://www.opengis.net/gml/3.2 http://schemas.opengis.net/gml/3.2.1/gml.xsd http://inspire.ec.europa.eu/schemas/cp/4.0 http://inspire.ec.europa.eu/schemas/cp/4.0/CadastralParcels.xsd"`

The only thing that change is the location of the theme schema. And CadastralParcels.xsd has the same substitutionGroup:

`<element name="CadastralParcel" substitutionGroup="gml:AbstractFeature" type="cp:CadastralParcelType">`

Thanks for any help provided!

**Comment by cportele** [comment]
The problem is the use of the namespace `http://inspire.ec.europa.eu/schemas/au/4.0/` in the AU.gml file. If you remove the trailing `/`(which is not included in the XML namespace of the published schema), the file should validate correctly.

This is also why the CP file validates as in that file the namespace is correct.

**Comment by OscarD31** [comment]
Aaagh! I'm kind of ashamed now. I didn't see the `/`.

Thanks!

**Comment by cportele** [comment]
No problem, so many slashes :-)
