### ISSUE TITLE
Metadata geographic bounding box error

### ISSUE THREAD

**Issue by MichalMed** [inspire-eu-validation/ets-repository#105]
http://inspire-sandbox.jrc.ec.europa.eu/etf-webapp/v2/TestRuns/EID1c76dbd1-644b-4b3e-b6fe-2851d7b1cca9.html

During the validation of metadata I've got following error on coordinates:

The metadata record set has 1 record(s) with errors for this assertion.
XML document 'metadata_CP.xml', record 'CZ-00025712-CUZK_SERIES-MD_CP': A dataset (series) metadata record must have a valid bounding box that defines the extent of the resource in geographic space. The bounding box is valid if: 1) it has four coordinates (given in decimal degree with a precision of at least 2 decimals), 2) both west- and east-bound longitude are greater than or equal to -180.00, and smaller than or equal to 180.00, 3) both south- and north-bound latitude are greater than or equal to -90.00, and smaller than or equal to 90.00, 4) south-bound latitude is smaller than or equal to north-bound latitude. At least one of these criteria is not fulfilled for one of the geographic bounding boxes of this metadata record. The provided values of this bounding box are: west-bound longitude = '12',  east-bound longitude = '19',  south-bound latitude = '48.5', north-bound latitude = '51.5'.

west-bound longitude = '12',  
east-bound longitude = '19',  
south-bound latitude = '48.5', 
north-bound latitude = '51.5'

I don't see any disconformance in here.

**Comment by cportele** [comment]
The issue is that the ATS (https://github.com/inspire-eu-validation/metadata/blob/master/iso-19115-19119/geographic-bounding-box.md) includes the assertion that all coordinates have "a precision of at least 2 decimals" (see item 1 in the error message), but the number have no or only 1 decimal.

That is, '12.00', '19.00', '48.50' and '51.50' should pass.

**Comment by MichalMed** [comment]
Repaired
