### ISSUE TITLE
Validation of Transport data-Association role:  route

### ISSUE THREAD

**Issue by cruizmon** [inspire-eu-validation/ets-repository#112]
Hello!
When I test a GML of MarkerPost FeatureType I receive next error.

XML document 'markerpost.xml', MarkerPost 'TN_MARKERPOST_VIAL_PK390600003365', property 'route': The property references a resource at 'http://www.ign.es/wfs-inspire/transportes?SERVICE=WFS&VERSION=2.0.0&REQUEST=GetFeature&OUTPUTFORMAT=application%2Fgml%2Bxml%3B+version%3D3.2&STOREDQUERY_ID=urn:ogc:def:query:OGC-WFS::GetFeatureById&ID=TN-RO_ROAD_VIAL_LI600000000099', but the resource is not an 'MarkerPost, Buoy or Beacon' or one of its known subtypes. Found: element 'Road' in namespace 'http://inspire.ec.europa.eu/schemas/tn-ro/4.0'.**

tn:route element is a link to a Road FeatureType that is the response of a GetFeatureByID stored query request. This response meets with WFS specification. So, what is the origin of the error?

GML: http://www.ign.es/wfs-inspire/transportes?SERVICE=WFS&VERSION=2.0.0&REQUEST=GetFeature&TYPENAME=tn:MarkerPost&count=1

Thanks.

**Comment by cportele** [comment]
This is an error. The abstract test case (https://github.com/inspire-eu-validation/data-tn/blob/3.2/tn-ia/features.md) states that the value of the `route` property must be a `TransportPoint`, but the application schema says it must be a `TransportLinkSet`, which in the road network means a `Road` or `ERoad`.

That is, the reference in the data looks correct, but the ATS and ETS need to be updated.

The test expression needs to be updated:

```
let $target := ('MarkerPost', 'Buoy', 'Beacon') 
...
let $messages := local:check-feature-references($hrefs, $target, 'MarkerPost, Buoy or Beacon', 'route')
```

```
let $target := ('Road', 'ERoad') 
...
let $messages := local:check-feature-references($hrefs, $target, 'Road or ERoad', 'route')
```
