### ISSUE TITLE
Coupled resource from services metadata

### ISSUE THREAD

**Issue by MichalMed** [inspire-eu-validation/ets-repository#113]
http://inspire-sandbox.jrc.ec.europa.eu/etf-webapp/v2/TestRuns/EIDf9672d4d-ad91-46d9-840c-ee36073a0aa7.html

I got one error, saying that coupled resource must be series or dataset, but it is not. Actually, it is: http://geoportal.cuzk.cz/getHTML.aspx?mode=Metadata&fnc=getRecord&identifierid=CZ-00025712-CUZK_SERIES-MD_AD

**Comment by cportele** [comment]
I think the reason is that the URL does not return a metadata record, but an HTML document in a 302-response with a link to the metadata record.

The general agreement in the ATS discussions was:

> The expected status code for HTTP GET and POST responses is 200, the expected status code for HTTP HEAD responses is 200 and 204. All other status codes indicate a failure (unless a test case specifies different conditions).
> ...
> Redirects (status codes 301, 302, and 303) are in general not allowed as they are not supported by the OGC Web Service standards. 

https://github.com/inspire-eu-validation/metadata/tree/1.3#http-status-codes

I assign @michellutz as any change would require a change in the ATSs (and would affect many texts).

**Comment by MichalMed** [comment]
It is weird, because I get the HTTP status code 200.

**Comment by MichalMed** [comment]
PS C:\Users\medm> wget http://geoportal.cuzk.cz/getHTML.aspx?mode=Metadata"&"fnc=getRecord"&"identifierid=CZ-00025712-CU
ZK_SERIES-MD_CP


StatusCode        : 200
StatusDescription : OK
Content           :
                    <csw:GetRecordByIdResponse xsi:schemaLocation="http://www.opengis.net/cat/csw/2.0.2 http://schemas.
                    opengis.net/csw/2.0.2/CSW-discovery.xsd" xmlns:csw="http://www.opengis.net/cat/csw/2.0.2" xmlns:ows
                    ...
RawContent        : HTTP/1.1 200 OK
                    Pragma: no-cache
                    NLB: AS-WWW2
                    tst: text/plain
                    Content-Length: 68871
                    Cache-Control: no-cache
                    Content-Type: text/xml; charset=utf-8
                    Date: Wed, 01 Nov 2017 14:46:45 GMT
                    Expires: -...
Forms             : {}
Headers           : {[Pragma, no-cache], [NLB, AS-WWW2], [tst, text/plain], [Content-Length, 68871]...}
Images            : {}
InputFields       : {}
Links             : {}
ParsedHtml        : mshtml.HTMLDocumentClass
RawContentLength  : 68871

**Comment by cportele** [comment]
Maybe wget in Windows is configured to automatically follow redirects?

Using cURL I get:

```
portele$ curl -i "http://geoportal.cuzk.cz/getHTML.aspx?mode=Metadata&fnc=getRecord&identifierid=CZ-00025712-CUZK_SERIES-MD_AD"

HTTP/1.1 302 Found
Location: /(S(z3uztzphguavnjux0mndua5k))/getHTML.aspx?mode=Metadata&fnc=getRecord&identifierid=CZ-00025712-CUZK_SERIES-MD_AD
Server: Microsoft-IIS/7.5
X-Powered-By: ASP.NET
NLB: AS-WWW2
tst:  text/plain
Date: Wed, 01 Nov 2017 17:22:02 GMT
Content-Length: 239

<html><head><title>Object moved</title></head><body>
<h2>Object moved to <a href="/(S(z3uztzphguavnjux0mndua5k))/getHTML.aspx?mode=Metadata&amp;fnc=getRecord&amp;identifierid=CZ-00025712-CUZK_SERIES-MD_AD">here</a>.</h2>
</body></html>
portele$ 
```

Note that the location changes with every request.

Try the original URL in a browser. You will see that it changes to one of the `/(S(xxx))/` URLs.

**Comment by MichalMed** [comment]
You're right, that's ugly. People from geoportal were saying that it is not possible, but they are all running windows.
From linux:
```
wget http://geoportal.cuzk.cz/getHTML.aspx?mode=Metadata"&"fnc=getRecord"&"identifierid=CZ-00025712-CUZK_SERIES-MD_CP
--2017-11-02 13:53:34--  http://geoportal.cuzk.cz/getHTML.aspx?mode=Metadata&fnc=getRecord&identifierid=CZ-00025712-CUZK_SERIES-MD_CP
Resolving geoportal.cuzk.cz (geoportal.cuzk.cz)... 2a00:1028:101:100::10:1, 195.245.209.228
Connecting to geoportal.cuzk.cz (geoportal.cuzk.cz)|2a00:1028:101:100::10:1|:80... connected.
HTTP request sent, awaiting response... 302 Found
Location: /(S(s0fv4wmalyeifhxqtzebxebc))/getHTML.aspx?mode=Metadata&fnc=getRecord&identifierid=CZ-00025712-CUZK_SERIES-MD_CP [following]
--2017-11-02 13:53:34--  http://geoportal.cuzk.cz/(S(s0fv4wmalyeifhxqtzebxebc))/getHTML.aspx?mode=Metadata&fnc=getRecord&identifierid=CZ-00025712-CUZK_SERIES-MD_CP


People from Land Survey told me to try it other way by using different attributes and I'm getting 200. Is this proper solution in your opinion?

```
michal@michal:~$ wget http://geoportal.cuzk.cz/SDIProCSW/service.svc/get?REQUEST=GetRecordById"&"SERVICE=CSW"&"VERSION=2.0.2"&"OUTPUTSCHEMA=http://www.isotc211.org/2005/gmd"&"ELEMENTSETNAME=full"&"Id=CZ-00025712-CUZK_SERIES-MD_CP
--2017-11-02 14:02:22--  http://geoportal.cuzk.cz/SDIProCSW/service.svc/get?REQUEST=GetRecordById&SERVICE=CSW&VERSION=2.0.2&OUTPUTSCHEMA=http://www.isotc211.org/2005/gmd&ELEMENTSETNAME=full&Id=CZ-00025712-CUZK_SERIES-MD_CP
Resolving geoportal.cuzk.cz (geoportal.cuzk.cz)... 2a00:1028:101:100::10:1, 195.245.209.228
Connecting to geoportal.cuzk.cz (geoportal.cuzk.cz)|2a00:1028:101:100::10:1|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 48478 (47K) [application/xml]
Saving to: ‘get?REQUEST=GetRecordById&SERVICE=CSW&VERSION=2.0.2&OUTPUTSCHEMA=http:%2F%2Fwww.isotc211.org%2F2005%2Fgmd&ELEMENTSETNAME=full&Id=CZ-00025712-CUZK_SERIES-MD_CP’

get?REQUEST=GetReco 100%[===================>]  47.34K  --.-KB/s    in 0.02s   

2017-11-02 14:02:22 (2.94 MB/s) - ‘get?REQUEST=GetRecordById&SERVICE=CSW&VERSION=2.0.2&OUTPUTSCHEMA=http:%2F%2Fwww.isotc211.org%2F2005%2Fgmd&ELEMENTSETNAME=full&Id=CZ-00025712-CUZK_SERIES-MD_CP’ saved [48478/48478]

```

**Comment by cportele** [comment]
Hi Michal, yes, if the metadata would use links like

http://geoportal.cuzk.cz/SDIProCSW/service.svc/get?REQUEST=GetRecordById&SERVICE=CSW&VERSION=2.0.2&OUTPUTSCHEMA=http://www.isotc211.org/2005/gmd&ELEMENTSETNAME=full&Id=CZ-00025712-CUZK_SERIES-MD_CP

the assertion should pass. You could try it out with a manually edited file that uses this type of link.

**Comment by MichalMed** [comment]
Ok, in that case my colleagues were right and I was wrong. I'm apologizing to them and changing links. And closing this issue.
