### ISSUE TITLE
Requesting the metadata record from the Service Feed with broken link

### ISSUE THREAD

**Issue by MPmurt** [inspire-eu-validation/ets-repository#114]
Hello.

I´m trying to validate AU data as ATOM ( http://inspire.maaamet.ee/arcgis/rest/directories/arcgisforinspire/public/au_MapServer/serviceatoma1.xml ), but having a trouble to understand a cause of one error. 

Atom [Download Service Feed document](http://inspire-sandbox.jrc.ec.europa.eu/etf-webapp//v2/TestTaskResults/EIDd7b223a3-535f-44e8-8050-ff9c8a10f23f/Attachments/EID5e9e1582-2fcb-445b-b84a-95f441a60316) (refered from the metadata document) must contain a describedby link (correct link is:
 [http://inspire.maaamet.ee/geoportal/rest/document?id=%7B8A81BFCC-E2A9-41BF-87BB-E6F5012BEF2F%7D](http://inspire.maaamet.ee/geoportal/rest/document?id=%7B8A81BFCC-E2A9-41BF-87BB-E6F5012BEF2F%7D)) and as I understand it does, but validator is requesting for some reason a broken link (http://inspire.maaamet.ee/geoportal/rest/document). 

Is that broken link problem caused by the code or is it some kind of validation error?

Report: http://inspire-sandbox.jrc.ec.europa.eu/etf-webapp/v2/TestRuns/EID3cab4542-0c32-4fde-a134-bd8b50f3968a.html#EID6359d6da-1e37-423f-b543-018979b665e2

Thanks!

**Comment by jonherrmann** [comment]
Hi, thanks for reporting this.

This is a bug in the test suite and seems to be very similar to issue #100.

**Comment by jonherrmann** [comment]
Ref https://github.com/interactive-instruments/etf-suitd/commit/2aa766326666174016f75799c187136f227b287b

**Comment by jonherrmann** [comment]
Feel free to reopen this issue if the changes did not resolve the issue or if something is still unclear.
