### ISSUE TITLE
The system has currently insufficient resources to process this request. Again.

### ISSUE THREAD

**Issue by alkrus** [inspire-eu-validation/ets-repository#118]
The validator is giving me following error when trying to execute a test:
"Test Run initialization failure
The system has currently insufficient resources to process this request. Please wait a few minutes and try again. If the problem persists, please contact the ETF system administrator of the server."

The problem has been there at least since Monday morning. The error text is suggesting to contact ETF system administrator which, as I see it, would be a better way to address the issue than to publish it here at GitHub but no contact information is provided. 

When can it be expected the ETF validator will be available to users again?

Thanks,
Alexander

See also issue #97 that describes the same problem. Back then it was discussed some solutions but I can't see that anything has been implemented?

**Comment by michellutz** [comment]
Sorry for the issue. We are looking into it.

**Comment by michellutz** [comment]
The application is back up and running (on the latest stable release and with additional memory). Sorry again for the inconvenience.
