### ISSUE TITLE
ATOM - OpenSeacrh validation: Issue with "Queries"

### ISSUE THREAD

**Issue by OscarD31** [inspire-eu-validation/ets-repository#122]
Good morning!

The TG says the following (Requirement 44):

> For each dataset available the OpenSearch description shall contain a ‗Query‘ element that has a ‗role‘ attribute with the value ―example‖ and ‗spatial_dataset_identifier_code‘ and ‗spatial_dataset_identifier_namespace‘ attributes together containing unique spatial dataset identifier. The value of the ‗crs‘ and ‗language‘ attributes shall be set to the values considered as the default ones by the service provider.

So, in the XML describing my OpenSearch engine I have added the following:

```
<Query role="example" inspire_dls:spatial_dataset_identifier_namespace="MY.CP" inspire_dls:spatial_dataset_identifier_code="CP.CODE" inspire_dls:crs="http://www.opengis.net/def/crs/EPSG/0/3042" language="es" format="GML" title="" count="1" />

<Query role="example" inspire_dls:spatial_dataset_identifier_namespace="MY.AU" inspire_dls:spatial_dataset_identifier_code="AU.CODE" inspire_dls:crs="http://www.opengis.net/def/crs/EPSG/0/3042" language="es" format="GML" title="" count="1" />
```

Due to the issues I reported for the ATOM validation, the test "**Query examples for each dataset**" was never run. But today I have realized I can "cheat" in my OpenSearch description document to force that test. I have just changed the return value of the Get Spatial Dataset operation to "application/atom+xml" to achieve that.

Sadly, the test "**Query examples for each dataset**" has failed, but I do not understand why. It gives two errors:

```
> The expected node 'os:Query' was not found in the response. XPath: /os:OpenSearchDescription/os:Query[@role='example' and @inspire_dls:crs]

> The expected node 'os:Query' was not found in the response. XPath: /os:OpenSearchDescription/os:Query[@role='example' and @inspire_dls:spatial_dataset_identifier_namespace and @inspire_dls:spatial_dataset_identifier_code]
```

For my surprise, the endpoint of that error is not the OpenSearch document. It's one of the datasets feed.

Is it looking for the Query tag in the dataset feed? The TG doesn't say anything about that.

I have tried to add one, but I'm still getting the same error.

What am I missing here?

I have attached the report.

Thanks for any help provided!

[ATOM_Report.zip](https://github.com/inspire-eu-validation/ets-repository/files/1481440/ATOM_Report.zip)

**Comment by jonherrmann** [comment]
Thanks Oscar, you are right, the assertions have to be moved one test step up, to check the OpenSearch document -and not the Describe Spatial Dataset response.

**Comment by OscarD31** [comment]
For a moment I was scared I was following an outdated TG.

Thanks for your answer!
