### ISSUE TITLE
Support for Annex III data tests Land Use (PLU)

### ISSUE THREAD

**Issue by tfr42** [inspire-eu-validation/ets-repository#126]
We would like to verify a direct-access download service (WFS 2.0) serving Annex III data theme Planned Land Use (PLU). Is a ETS available which verifies the IR and TG Requirements for PLU as specified in [INSPIRE Data Specification on Land Use – Technical Guidelines](https://inspire.ec.europa.eu/id/document/tg/lu)?

**Comment by cportele** [comment]
Currently there is no ETS for any annex II/III theme / application schema.

What is available are the general tests that are not specific to an application schema - look for the group of ETSs labeled "Interoperable data sets in GML (Guidelines for the Encoding of Spatial Data version 3.3)".

**Comment by tfr42** [comment]
OK, thanks. Found the source file in https://github.com/inspire-eu-validation/ets-repository/blob/master/data-encoding/inspire-gml/ets-inspire-gml-bsxets.xml
