### ISSUE TITLE
md-iso.c.3: Dataset linkage: unable to find valid certification path to requested target

### ISSUE THREAD

**Issue by heidivanparys** [inspire-eu-validation/ets-repository#128]
I get the following error, I am not sure how to deal with it, would it be possible to give more info on what exactly is wrong? I tried with both HTTP and HTTPS to see if that would make any difference, but it doesn't.

Is it an issue with the test or an issue with (the certification) of the website? Any pointers would be great.

> The metadata record set has 1 record(s) with errors for this assertion.
> XML document 'test_download_kortforsyningen.xml', record '7eace144-c529-4c1f-83be-d98fc4e57656': The metadata record has a linkage property, but it references a resource at 'http://download.kortforsyningen.dk/content/stednavne' that cannot be accessed. An exception occured when accessing the resource. Error message: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
> XML document 'test_download_kortforsyningen.xml', record '7eace144-c529-4c1f-83be-d98fc4e57656': The metadata record has a linkage property, but it references a resource at 'https://download.kortforsyningen.dk/content/stednavne' that cannot be accessed. An exception occured when accessing the resource. Error message: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

Test report: http://inspire-sandbox.jrc.ec.europa.eu/etf-webapp//v2/TestRuns/EIDbbca486e-49a5-448f-af75-56e724e8ab24.html
Test: md-iso.c.3: Dataset linkage
Assertion URI: http://inspire-sandbox.jrc.ec.europa.eu/etf-webapp//v2/TestRuns/EIDbbca486e-49a5-448f-af75-56e724e8ab24.html?lang=en#EID679ac0ef-2301-44ac-9095-d05e9275c6e0 
File: [test_download_kortforsyningen.txt](https://github.com/inspire-eu-validation/ets-repository/files/1528889/test_download_kortforsyningen.txt)

**Comment by jonherrmann** [comment]
Ref https://github.com/inspire-eu-validation/ets-repository/issues/86

@robsgnao could you check if the RCA (COMODO) of this cert is in the trust store:
https://www.ssllabs.com/ssltest/analyze.html?d=download.kortforsyningen.dk ?

**Comment by robsgnao** [comment]
COMODO Root CA Certificate was present, while the domain validation Certificate was not (Intermediate certification certificate for domain validated SSL certificated); just added, change will be operational after midnight CET.

**Comment by heidivanparys** [comment]
I tested again and the error regarding the valid certification path is not present anymore.

**Comment by robsgnao** [comment]
The SSL-related issue is not present while using OpenJDK instead of Oracle JDK.
Validator hosted at JRC has been switched to OpenJDK yesterday.
