### ISSUE TITLE
"Test Run initialization failure" while testing WFS-service"

### ISSUE THREAD

**Issue by LarsAllstrin** [inspire-eu-validation/ets-repository#131]
- [ ] a link to the Test Report: N/A

- [ ] the name of the Test that failed: "unable to find valid certification path to requested target"

- [ ] the URL of your service: https://geokatalog.sjofartsverket.se/MapService/wfs.axd/TN_TransportNetwork?Service=WFS&version=2.0.0&request=getFeature&typenames=tn-w:WaterwayLink

Hi!

I am trying to run a WFS-service through the Validation tool but I get the error mentioned above. The service seems fine to me while trying to access it via Chrome for example (using the link pasted above)

The error-message I receive does not add any extra information pertaining to what actually goes wrong.

Best regards,
Lars

**Comment by jonherrmann** [comment]
Hi Lars,

this looks very similar to issue #86.

@robsgnao could you please check the certificate for this issue?

https://www.ssllabs.com/ssltest/analyze.html?d=geokatalog.sjofartsverket.se

**Comment by robsgnao** [comment]
DigiCert Root CA certificate was present, SHA2 intermediate certificate was not; just added, should be operational tomorrow morning (4am onwards).

**Comment by LarsAllstrin** [comment]
Cheers @jonherrmann & @robsgnao !

**Comment by robsgnao** [comment]
The SSL-related issue is not present while using OpenJDK instead of Oracle JDK.
Validator hosted at JRC has been switched to OpenJDK yesterday.
