### ISSUE TITLE
Question collection of metadata records

### ISSUE THREAD

**Issue by heidivanparys** [inspire-eu-validation/ets-repository#138]
Are there any requirements regarding how a collection of metadata records should be sent to the validator?

So far, when validating more than one record at once, I've been sending the GetRecordsResponse from the CSW server. However, I finally realized that there is a conflict with the GML versions used:

- CSW 2.0.2. depends on the filter encoding specification,namespace http://www.opengis.net/ogc, located at http://schemas.opengis.net/filter/1.1.0/filter.xsd, which again depends on GML 3.1.1
- the metadata schemas used by CSW 2.0.2 are the ones at http://schemas.opengis.net/iso/19139/20060504/, which depend on GML 3.2.0.

There are some incompatibilities there, and as a result, it seems to be impossible to have a file that is XML Schema valid, when simply sending the GetRecordsResponse to the validator, see e.g. http://inspire-sandbox.jrc.ec.europa.eu/etf-webapp//v2/TestRuns/EID49e0896c-4e85-435c-8f2f-9a2396da3eb2.html

```
The dataset has 1 file(s) with errors for this assertion.
XML document 'minimal_metadata_wrapped_csw.xml': The file has 5 schema validation error(s).
XML document 'minimal_metadata_wrapped_csw.xml': http://schemas.opengis.net/iso/19139/20060504/gco/gcoBase.xsd, 31:59: src-resolve: Cannot resolve the name 'gml:NilReasonType' to a(n) 'type definition' component.
XML document 'minimal_metadata_wrapped_csw.xml': http://schemas.opengis.net/iso/19139/20060504/gco/gcoBase.xsd, 31:59: src-resolve: Cannot resolve the name 'gml:NilReasonType' to a(n) 'simpleType definition' component.
XML document 'minimal_metadata_wrapped_csw.xml': http://schemas.opengis.net/iso/19139/20060504/gsr/spatialReferencing.xsd, 18:39: src-resolve: Cannot resolve the name 'gml:AbstractCRS' to a(n) 'element declaration' component.
XML document 'minimal_metadata_wrapped_csw.xml': http://schemas.opengis.net/iso/19139/20060504/gts/temporalObjects.xsd, 18:49: src-resolve: Cannot resolve the name 'gml:AbstractTimePrimitive' to a(n) 'element declaration' component.
XML document 'minimal_metadata_wrapped_csw.xml': http://schemas.opengis.net/iso/19139/20060504/gss/geometry.xsd, 29:44: src-resolve: Cannot resolve the name 'gml:AbstractGeometry' to a(n) 'element declaration' component.

```

Therefore, I was thinking to wrap the metadatarecords in a custom wrapper, e.g. see the example below. With that wrapper, the errors reported above do not appear.

However, I would like to know

- if this way of sending metadata records could cause any problems?
- if a similar construction maybe already exists?

```
<schema
  xmlns="http://www.w3.org/2001/XMLSchema"
  targetNamespace="https://www.geodata-info.dk/schemas/wrapper"
  xmlns:gi="https://www.geodata-info.dk/schemas/wrapper"
  xmlns:gmd="http://www.isotc211.org/2005/gmd"
  elementFormDefault="qualified">
  <import namespace="http://www.isotc211.org/2005/gmd" schemaLocation="http://schemas.opengis.net/iso/19139/20060504/gmd/gmd.xsd" />
  
  <element name="Wrapper" type="gi:WrapperType" />
  <complexType name="WrapperType">
    <sequence>
      <element ref="gmd:MD_Metadata" minOccurs="0" maxOccurs="unbounded" />
    </sequence>
  </complexType>
</schema>
```

**Comment by cportele** [comment]
It is not really clear to me why the problem occurs. Using a GetRecordsResponse should be ok. I have used GetRecordsResponses from several discovery services without any errors that are similar to the ones you have described.

I am surprised that http://www.opengis.net/ogc is imported by the GetRecordsResponse. Which elements of Filter 1.1 are used in the GetRecordsResponse? Do you have an example URL to a GetRecordsResponse that causes errors? Thanks.

If http://www.opengis.net/ogc is imported, there is indeed a conflict as then the namespace http://www.opengis.net/gml is used for two different sets if schema documents (the GML 3.1.1 schema and the unpublished GML 3.2.0 schema).

**Comment by heidivanparys** [comment]
Steps taken:

1. sent request to https://geodata-info.dk/srv/eng/csw
```
<soap:Envelope xmlns:soap="http://www.w3.org/2003/05/soap-envelope">
	<soap:Header/>
	<soap:Body xmlns:soap="http://www.w3.org/2003/05/soap-envelope">
		<csw:GetRecords
				xmlns:csw="http://www.opengis.net/cat/csw/2.0.2"
				xmlns:ogc="http://www.opengis.net/ogc"
				xmlns:gmd="http://www.isotc211.org/2005/gmd"
				service="CSW"
				version="2.0.2"
				outputFormat="application/xml"
				outputSchema="http://www.isotc211.org/2005/gmd"
				resultType="results">
			<csw:Query typeNames="gmd:MD_Metadata">
				<csw:ElementSetName>full</csw:ElementSetName>
				<csw:Constraint version="1.1.0">
					<ogc:Filter>
						<ogc:And>
							<ogc:Or>
								<ogc:PropertyIsEqualTo>
									<ogc:PropertyName>MetadataPointOfContact</ogc:PropertyName>
									<ogc:Literal>Styrelsen for Dataforsyning og Effektivisering, Energi-, Forsynings- og Klimaministeriet</ogc:Literal>
								</ogc:PropertyIsEqualTo>
								<ogc:PropertyIsEqualTo>
									<ogc:PropertyName>MetadataPointOfContact</ogc:PropertyName>
									<ogc:Literal>Agency for Data Supply and Efficiency</ogc:Literal>
								</ogc:PropertyIsEqualTo>
							</ogc:Or>
							<ogc:PropertyIsEqualTo>
								<ogc:PropertyName>Subject</ogc:PropertyName>
								<ogc:Literal>INSPIRE</ogc:Literal>
							</ogc:PropertyIsEqualTo>
							<ogc:PropertyIsEqualTo>
								<ogc:PropertyName>Subject</ogc:PropertyName>
								<ogc:Literal>stednavne</ogc:Literal>
							</ogc:PropertyIsEqualTo>
						</ogc:And>
					</ogc:Filter>
				</csw:Constraint>
			</csw:Query>
		</csw:GetRecords>
	</soap:Body>
</soap:Envelope>
```
2. Modified schemalocation to point to http://schemas.opengis.net/iso/19139/20060504/ instead of http://www.isotc211.org/2005/ (#136 , this will be fixed in our GeoNetwork installation)
3. Sent 
[file with metadata](https://github.com/inspire-eu-validation/ets-repository/files/1663217/test_sdfe_inspire_stednavne.txt)
 to validator: http://inspire-sandbox.jrc.ec.europa.eu/etf-webapp//v2/TestRuns/EID2fb40c01-5b5f-47f0-ab9f-95e71fd29f49.html?lang=en#EID9ad42a1c-4fc4-4c03-8332-0af311e7de8b

```
The dataset has 1 file(s) with errors for this assertion.
XML document 'test_sdfe_inspire_stednavne.xml': The file has 7 schema validation error(s).
XML document 'test_sdfe_inspire_stednavne.xml': http://schemas.opengis.net/iso/19139/20060504/gco/gcoBase.xsd, 31:59: src-resolve: Cannot resolve the name 'gml:NilReasonType' to a(n) 'type definition' component.
XML document 'test_sdfe_inspire_stednavne.xml': http://schemas.opengis.net/iso/19139/20060504/gco/gcoBase.xsd, 31:59: src-resolve: Cannot resolve the name 'gml:NilReasonType' to a(n) 'simpleType definition' component.
XML document 'test_sdfe_inspire_stednavne.xml': http://schemas.opengis.net/iso/19139/20060504/gsr/spatialReferencing.xsd, 18:39: src-resolve: Cannot resolve the name 'gml:AbstractCRS' to a(n) 'element declaration' component.
XML document 'test_sdfe_inspire_stednavne.xml': http://schemas.opengis.net/iso/19139/20060504/gts/temporalObjects.xsd, 18:49: src-resolve: Cannot resolve the name 'gml:AbstractTimePrimitive' to a(n) 'element declaration' component.
XML document 'test_sdfe_inspire_stednavne.xml': http://schemas.opengis.net/iso/19139/20060504/gss/geometry.xsd, 29:44: src-resolve: Cannot resolve the name 'gml:AbstractGeometry' to a(n) 'element declaration' component.
XML document 'test_sdfe_inspire_stednavne.xml': 186:115: cvc-complex-type.2.4.d: Invalid content was found starting with element 'gml:TimePeriod'. No child element is expected at this point.
XML document 'test_sdfe_inspire_stednavne.xml': 503:88: cvc-complex-type.2.4.d: Invalid content was found starting with element 'gml:TimePeriod'. No child element is expected at this point.
```

4.  [Modified file with metadata](https://github.com/inspire-eu-validation/ets-repository/files/1663218/test_sdfe_inspire_stednavne_gml_on_top.txt) so the gml namespace is declared at the top: http://inspire-sandbox.jrc.ec.europa.eu/etf-webapp//v2/TestRuns/EID87e47d8f-1c59-40d6-bda4-ae8ae4b944fb.html?lang=en#EID5b93b643-ad4f-417f-af04-5ee2db40bbe9

```
The dataset has 1 file(s) with errors for this assertion.
XML document 'test_sdfe_inspire_stednavne_gml_on_top.xml': The file has 2 schema validation error(s).
XML document 'test_sdfe_inspire_stednavne_gml_on_top.xml': http://schemas.opengis.net/filter/1.1.0/filter.xsd, 204:53: src-resolve: Cannot resolve the name 'gml:_Geometry' to a(n) 'element declaration' component.
XML document 'test_sdfe_inspire_stednavne_gml_on_top.xml': http://schemas.opengis.net/filter/1.1.0/filter.xsd, 226:50: src-resolve: Cannot resolve the name 'gml:_Geometry' to a(n) 'element declaration' component.
```

![image](https://user-images.githubusercontent.com/11427611/35379701-3998534c-01b7-11e8-8800-b70bd358bc3f.png)

**Comment by cportele** [comment]
Thanks! Looking at this, I do not understand how any strict validation of a CSW 2.0.2 GetRecordsResponse with GMD MD_Metadata can validate. Since this always uses GML 3.1.1 and the CSW-2.0.2-specific GML 3.2.0 - different schemas that use the same namespace - this will always report issues.

(NB: I just looked at the CSW 2.0.2 GetRecordsResponses that I had used for testing before and they indeed have the same issue, too. I overlooked it as all the files had other validation issues in gmd:MD_Metadata, too.)

As it looks now, there is not much we can do in the validator, this is an inherent defect in the CSW ISO AP specification.

OK, so what are the options, if the analysis is correct:

* Fix the standard and all implementations. Unlikely to happen.
* Drop requirement for schema validation in the metadata tests. Probably also not acceptable as schema issues seem to be quite common.
* No longer allow that csw:GetRecordResponse may be used. Either invent a new collection wrapper for gmd:MD_Metadata records just for the validator or just allow gmd:MD_Metadata. Not very good...
* Change the schema validation test case to a manual test and request that the validation result is inspected to confirm that only errors from the CSW ISO AP bug are reported.
* Implement some special treatment that a csw:GetRecordResponse is transformed to another representation that does not have this issue. This is similar to the wrapper in the third option, just hidden inside the validator.
* ...

This should be discussed by the MIG sub-group.

**Comment by heidivanparys** [comment]
Another option could be to remove any error messages that report errors in another file than the file containing metadata (and to clearly mention this behaviour in the description of the test).

Eclipse gives the option to display a warning or an error when a "referenced file contains errors", or to ignore these kind of messages altogether.

![image](https://user-images.githubusercontent.com/11427611/35386426-4bbc34de-01cc-11e8-8911-7d182ee0e8c7.png)

![image](https://user-images.githubusercontent.com/11427611/35386471-7930d5aa-01cc-11e8-90b5-00954c86c1db.png)

See https://github.com/search?l=Java&q=org%3Aeclipse+%22referenced+file+contains+errors%22&type=Code and https://github.com/eclipse/webtools.sourceediting/blob/ac15f0565f5b71b5bd50e93ca10010031888050d/xml/bundles/org.eclipse.wst.xml.core/src-validation/org/eclipse/wst/xml/core/internal/validation/core/ValidationInfo.java for the implementation.

**Comment by cportele** [comment]
The current built-in validation library does not support this. To support additional options would require a custom approach to validation (https://github.com/interactive-instruments/etf-webapp/issues/61) - which in fact would also allow to construct a set of schema documents that would avoid such errors.

**Comment by michellutz** [comment]
The OGC has finally published bugfix releases for the CSW ISO AP and ISO service metadata schemas that fix the GML schema import issues:
- http://schemas.opengis.net/csw/2.0.2/profiles/apiso/1.0.0/apiso.xsd
- http://schemas.opengis.net/iso/19139/20070417/srv/

When changing 
- the schema locations in the metadata document from http://schemas.opengis.net/iso/19139/20060504/... to http://schemas.opengis.net/iso/19139/20070417/... and
- the gml namespace from http://www.opengis.net/gml to http://www.opengis.net/gml/3.2
the document validates.

[test_sdfe_inspire_stednavne_fixed.txt](https://github.com/inspire-eu-validation/ets-repository/files/1837123/test_sdfe_inspire_stednavne_fixed.txt)

**Comment by michellutz** [comment]
[2017.4 meeting 2018-03-16] It should be checked whether the OGC schema fix solves the issues (it seems that it does - see previous comment). Independently, the ETF improvement to allow a custom approach to validation (interactive-instruments/etf-webapp#61) should be prioritised for the further ETF development.

**Comment by michellutz** [comment]
@heidivanparys If you agree, I would suggest to close this issue.

**Comment by heidivanparys** [comment]
I am not sure that it completely solves the issue, as CSW 2.0.2 still refers to GML 3.1.1. I tried to test but didn't reach a final conclusion yet.

However, in any case we'll have to update our Geonetwork installation at some point, as that currently uses the 20060504 schemas.

So ok with me to close this issue for now, @michellutz

**Comment by michellutz** [comment]
[2017.4 meeting 2018-04-19] The issue can be closed.
