### ISSUE TITLE
Non-unique IDs in ETS

### ISSUE THREAD

**Issue by jonherrmann** [inspire-eu-validation/ets-repository#14]
The ETS in the repo possess non-unique IDs.

2 examples for EID4c53a8c7-7cac-4531-982b-d03eb48ffa77:

https://github.com/inspire-eu-validation/ets-repository/blob/master/data-ps/ps-as/ets-ps-as-bsxets.xml

https://github.com/inspire-eu-validation/ets-repository/blob/master/data-ad/ad-as/ets-ps-as-bsxets.xml

The same issue applies to Test Case/Assertion/... IDs. That problem will only be recognizable after startup, when two ETS definitions are queried as XML and the returned collection contains non-unique IDs. The schema prohibits non-unique IDs and therefore an error will be reported.

It would be good to have a (groovy?) script for checking the IDs, which can be executed by ETS developers or a CI. This could be also integrated in the ETF later.

**Comment by cportele** [comment]
Agreed.

In this case it is no surprise as the data-ad and data-tn folders are right now just copies of the data-ps directory. I will delete these directories in the master branch. They can be added later again when the proper ETSs are available.
