### ISSUE TITLE
Validation fails with multilanguage service metadata

### ISSUE THREAD

**Issue by montsemarco** [inspire-eu-validation/ets-repository#144]
Hi,

When passing the test '**INSPIRE profile based on EN ISO 19115 and EN ISO 19119**' to a **service** multilingual metadata (that is, a metadata with branch //gmd:identificationInfo/**srv:SV_ServiceIdentification**), I got an error informing that 'gmd:PT_FreeText_PropertyType' cannot be resolved for all multilingual branches.  

However, if this test is passed to a multilingual metadata (metadata with branch ///gmd:identificationInfo/gmd:MD_DataIdentification), the test pass properly.

This is the link to the Test Report: http://inspire-sandbox.jrc.ec.europa.eu/etf-webapp/v2/TestRuns/EID4de9095d-d9f3-4837-9433-34fc49fd897f.html

Thanks in advance and best regards,
M. Marco

**Comment by jonherrmann** [comment]
Hi Marco,

does the file validate on you machine?

We have no access to uploaded data. Please note that issues cannot be fixed for services/datasets that we cannot access.

**Comment by montsemarco** [comment]
Hi Jon,

I attach a multilingual service metadata as example,

Thanks and best regards,
M. Marco

[ServiceMetadata.zip](https://github.com/inspire-eu-validation/ets-repository/files/1774157/ServiceMetadata.zip)

**Comment by cportele** [comment]
The errors messages are correct. The root element is:

`<gmd:MD_Metadata ... xsi:schemaLocation="http://www.isotc211.org/2005/srv http://schemas.opengis.net/iso/19139/20060504/srv/srv.xsd">`

This only declares the schema location of the srv schema, not the gmd schema. The srv schema seems to import only parts of the gmd schema, and the parts exclude the [freeText.xsd](http://schemas.opengis.net/iso/19139/20060504/gmd/freeText.xsd) schema document. This results in the validation errors.

If you change the opening tag of the root element to the following, the errors should go away:

`<gmd:MD_Metadata ... xsi:schemaLocation="http://www.isotc211.org/2005/gmd http://schemas.opengis.net/iso/19139/20060504/gmd/gmd.xsd http://www.isotc211.org/2005/srv http://schemas.opengis.net/iso/19139/20060504/srv/srv.xsd">`

**Comment by montsemarco** [comment]
Hi Clemens,
Thanks for the correction. Now the metadata validates properly.
Best regards
