### ISSUE TITLE
Iterate over Describe Spatial Dataset URL

### ISSUE THREAD

**Issue by agarvicu** [inspire-eu-validation/ets-repository#164]
We are implementing the following ATOM service (https://inspire.larioja.org/atom/) and we get an error when passing it through the ETF INSPIRE validator . We get the following error: "Iterate over Describe Spatial Dataset URL". We do not know how to solve it. 

- [ http://inspire-sandbox.jrc.ec.europa.eu/etf-webapp/v2/TestRuns/EID873ab6dd-c660-4429-9fee-46fd3cf402e7.html] a link to the Test Report
- [inspire-sandbox.jrc.ec.europa.eu/etf-webapp//v2/TestRuns/EID873ab6dd-c660-4429-9fee-46fd3cf402e7.html?lang=en#EIDb013d66e-0163-1000-02ab-53d993029760 ] Assertion URI`
- [https://inspire.larioja.org/atom/ ] the URL of the service

**Comment by jonherrmann** [comment]
Thanks for reporting!

The bug was fixed in the Predefined-Atom ETS version 1.0.3 . Please note the fix has **not** yet been deployed to the INSPIRE validator.
