### ISSUE TITLE
dataset linkage image/tiff as media type for WMS

### ISSUE THREAD

**Issue by kodebaets** [inspire-eu-validation/ets-repository#169]
We have a metadata file for a dataset with a dataset linkage. The linkage property is an URL to a WMS GetMap request. The media type included in the request is ‘image/tiff’, which is a media type documented in the register (http://inspire.ec.europa.eu/media-types/image).

However, we are getting the following error in the ETF-validator:
“_The metadata record has a linkage property, which references a resource with media type 'image/tiff' at 'https://inspire.informatievlaanderen.be/raadpleegdiensten/hy/wms?SERVICE=WMS&REQUEST=GetMap&FORMAT=image/tiff&TRANSPARENT=TRUE&STYLES=HY.PhysicalWaters.Catchments.Default&VERSION=1.3.0&LAYERS=HY.PhysicalWaters.Catchments&WIDTH=1920&HEIGHT=840&CRS=EPSG:3857&BBOX=280525,6557859,661237,6712007' which is not one of the media types indicating an INSPIRE network service. Please review the resource to check that it meets the linkage requirements; specifically, if the resource is a webpage, check that it provides further instructions or a client application that directly accesses the service._”

We are wondering if this error is correct and if so, how should we adjust our dataset linkage? 
Where do we find the correct list / thesaurus of media types to be used?

Best regards.  

Test report: http://inspire-sandbox.jrc.ec.europa.eu/etf-webapp/v2/TestRuns/EIDe7ce26c6-9cde-4162-b433-f441d071608c.html

Metadata record: [b3d6fef2-6a22-4961-add2-a548d9157032 (6).zip](https://github.com/inspire-eu-validation/ets-repository/files/2136974/b3d6fef2-6a22-4961-add2-a548d9157032.6.zip)

**Comment by cportele** [comment]
The error is reported because a link to a TIFF image does not meet any of the options specified in the requirement (see the text in the test report):

> TG Requirement 3: If a linkage for data is available, the Resource Locator shall be a valid URL providing one of the following: a link to a web page with further instructions, a link to a service capabilities document, a link to the service WSDL document (SOAP Binding), a link to a client application that directly accesses the service.

If the link would be to https://inspire.informatievlaanderen.be/raadpleegdiensten/hy/wms?SERVICE=WMS&REQUEST=GetCapabilities instead, there should be no error.

**Comment by bcosyn** [comment]
What if you have for every layer 2 times a "gmd:CI_OnlineResource". One with a valid and reachable Getcapabilities request reference and one with a  valid and reachable Getmap request. How do we deal with this?

**Comment by cportele** [comment]
Currently it would also raise an error, because each URL is tested. The wording of the requirement is not really clear about whether each URL needs to be such a URL or that there has to be at least one that meets the condition. I read it as the former, but maybe that was not the intention.

Maybe something to discuss in the MIG-T sub-group?

**Comment by cportele** [comment]
I have set the tag so that it will be on the agenda of the MIG-T subgroup.

**Comment by michellutz** [comment]
I think this issue was already discussed and resolved in #117. It seems that the proposed solution has not yet been implemented. I'll chase this up.

**Comment by cportele** [comment]
Yes, @michellutz ! Thanks, I forgot about that thread.

**Comment by michellutz** [comment]
I suggest to close the issue. I have reopened issue #117 and flagged it for implementation.
