### ISSUE TITLE
Dataset conformity - Regulation

### ISSUE THREAD

**Issue by inakidiazdecerio** [inspire-eu-validation/ets-repository#186]
This issue refers to https://github.com/inspire-eu-validation/community/issues/2.

The title text in the CI_Citation should be the title in the relevant MD language. The correct titles in the different languages are available in the language-specific files at http://inspire.ec.europa.eu/schemas/common/1.0/enums/.

It was suggested to allow different capitalisation of words and also additional spaces. At this moment, additional spaces are allowed at the beginning, at the end and in the middle of the words of the title. The ETS eliminates spaces at the beginning and at the end and generates a string with only one whitespace between words.

To fix this issue, we propose to eliminate all whitespaces in the string when are compared. 

A new branch is created with the implementation for the solution.

**Comment by MarcoMinghini** [comment]
The [related issue](https://github.com/inspire-eu-validation/community/issues/2) has been tested and solved.

@inakidiazdecerio if this issue is the same, can we keep the other one (until the fix is deployed in production also) and close this one?

**Comment by inakidiazdecerio** [comment]
Yes @MarcoMinghini, you can close this issue.
