### ISSUE TITLE
The metadata test fails with multilanguaje metadata

### ISSUE THREAD

**Issue by montsemarco** [inspire-eu-validation/ets-repository#188]
Al our metadata that were validating a few moths ago now fail. 
The report says that there is not a GEMET controlled vocabulary and that there is not title and date. 
That information is included in the metadata and, as I mentioned, the last time that I validated the metadata they passed the test without any problem.

Our metadata are multilingual.

- Link to the Test Report: http://inspire-sandbox.jrc.ec.europa.eu/etf-webapp/v2/TestRuns/EID244476b1-f464-480f-a09d-5348094cfcad.html
- Name of the Test that failed: Conformance class: INSPIRE Profile based on EN ISO
- URL of one of the metadata that fails: http://sitmun.diba.cat/metadades/srv/cat/xml_iso19139?id=5066

Thanks for your help and support,

**Comment by inakidiazdecerio** [comment]
Hello @montsemarco,

Thank you for your reporting the issues. Those two issues have been already reported and will be fixed soon. 

The issue https://github.com/inspire-eu-validation/ets-repository/issues/180 is under discussion and the https://github.com/inspire-eu-validation/ets-repository/issues/186 under development. 

We will let you know when these issues are fixed.

**Comment by inakidiazdecerio** [comment]
In addition, to fix the "md-iso.c.4: Dataset conformity" error, one of the citation elements shall contain title of the [Regulation 1089/2010]. The titles are listed in different languages in this url:

http://inspire.ec.europa.eu/schemas/common/1.0/enums/

The correct title in spanish is:

`REGLAMENTO (UE) No 1089/2010 DE LA COMISIÓN de 23 de noviembre de 2010 por el que se aplica la Directiva 2007/2/CE del Parlamento Europeo y del Consejo en lo que se refiere a la interoperabilidad de los conjuntos y los servicios de datos espaciales`

In the metadata that you have provided:

`Reglamento (UE) no 1089/2010 de la Comisión, de 23 de noviembre de 2010, por el que se aplica la Directiva 2007/2/CE del Parlamento Europeo y del Consejo en lo que se refiere a la interoperabilidad de los conjuntos y los servicios de datos espaciales`

As you can see, there are two additional commas in the text that make the test fail. At this moment we are developing a solution to skip all whitespaces and avoid uppercase-lowercase discrepancies. Unfortunatelly, the rest of the text should be as it is specified in the enumeration scheema.

@montsemarco, we will come back to you when the mentioned solution is ready.

**Comment by montsemarco** [comment]
I will remove the commas in the text. 
Thanks a lot for your support

**Comment by AsuncionJuntaExtremadura** [comment]
inakidiazdecerio commented on 30 Oct

The correct title in spanish is:
REGLAMENTO (UE) No 1089/2010 DE LA COMISIÓN de 23 de noviembre de 2010 por el que se aplica la Directiva 2007/2/CE del Parlamento Europeo y del Consejo en lo que se refiere a la interoperabilidad de los conjuntos y los servicios de datos espaciales

http://inspire.ec.europa.eu/schemas/common/1.0/enums/enum_spa.xsd
REGLAMENTO (UE) N o 1089/2010 DE LA COMISIÓN de 23 de noviembre de 2010 por el que se aplica la Directiva 2007/2/CE del Parlamento Europeo y del Consejo en lo que se refiere a la interoperabilidad de los conjuntos y los servicios de datos espaciales

Pliease, correct "N o" by "No"
