### ISSUE TITLE
Hydrography dataset only validates when using wfs:FeatureCollection

### ISSUE THREAD

**Issue by JohannaOtt** [inspire-eu-validation/ets-repository#200]
I validated a Hydrography dataset using a gml:FeatureCollection and gmlas.b.2 (Assertion ID EID0eaac0f2-9ab3-44ab-9f02-4ee0a1587d14) fails with the error message "XML document 'testExport_fmlFeatureCollection.gml': The file has 1 schema validation error(s).
XML document 'testExport_fmlFeatureCollection.gml': 3:55: cvc-complex-type.2.4.a: Invalid content was found starting with element '{"http://inspire.ec.europa.eu/schemas/net/4.0":Network}'. One of '{"http://www.opengis.net/gml/3.2":AbstractFeature}' is expected." The test report can be found here: http://inspire-sandbox.jrc.ec.europa.eu/etf-webapp/v2/TestRuns/EIDb654243c-c596-44e6-9f84-61a82317f7b7.html

It does validate when using a wfs:FeatureCollection. Reading https://github.com/inspire-eu-validation/data-encoding/blob/3.3/inspire-gml/basic.md The test report can be found here: http://inspire-sandbox.jrc.ec.europa.eu/etf-webapp/v2/TestRuns/EID66c9097b-a544-4684-83ff-8fa015f7df20.html I would expect both versions to validate. Is that an incorrect assumption?

If needed, I can of course send the files tested via email.

All the best

Johanna

**Comment by inakidiazdecerio** [comment]
Dear @JohannaOtt,

Thanks for reporting the issue. Could you attach the tested files in a ZIP format?

Regards,
Iñaki

**Comment by JohannaOtt** [comment]
Dear @inakidiazdecerio ,

Here are the two versions of the dataset I tested: 
[HY-N.zip](https://github.com/inspire-eu-validation/ets-repository/files/2937139/HY-N.zip)

Thank you in advance, all the best

Johanna

**Comment by inakidiazdecerio** [comment]
@JohannaOtt it seems that in your file "testExport_gmlFeatureCollection.gml" the namespace http://inspire.ec.europa.eu/schemas/net/4.0 is missing. 

To fix the issue, you should have to add "http://inspire.ec.europa.eu/schemas/net/4.0 http://inspire.ec.europa.eu/schemas/net/4.0/Network.xsd" in the atributte xsi:schemaLocation (see the attached image).

Best regards.

![schemaLocation](https://user-images.githubusercontent.com/36446028/54346610-abc4cd00-4645-11e9-98f3-811514db1bd4.png)

**Comment by JohannaOtt** [comment]
Hi @inakidiazdecerio,

Thank you for the hint. I also got pointed to the fact that it also helps to place the object using the 'net' namespace at a later point in the GML file.
Once the validator checked an object from the 'hy-n' namespace it is also able to successfully validate against the namespaces from all schemaLocations imported into the 'hy-n' schema.

All the best
Johanna
