### ISSUE TITLE
GetRecordByID doesn't work

### ISSUE THREAD

**Issue by Michael-81** [inspire-eu-validation/ets-repository#209]
Ticket: #96:

Metadatatest doesn't work:   "Es wurden keine Dateinen mit der Endung GML / XML gefunden!"

https://mdi-sh.org/nokis/servants/de/disy/preludio2/service/cat/csw/v_2_0_2/GetRecordByIdServant$Get?Service=CSW&Request=GetRecordById&Version=2.0.2&outputSchema=http://www.isotc211.org/2005/gmd&element=full&id=c6716a2e-8573-492b-91cb-0d144e6daef3

A GetGecordByID Request has no .xml ending in it's encoding!

**Comment by Michael-81** [comment]
???? No answer to GetRecordByID Requests?

**Comment by michellutz** [comment]
Dear Michael, could you please re-post your issue in the community forum at https://github.com/inspire-eu-validation/community/issues/new?template=problem.md ideally providing some further details of the error you are encountering?

Thanks.

**Comment by Michael-81** [comment]
I opened a ticket in the community section.

for me it's a bug that the validator doesn't support the GetRecordByID Request for technical Testing of INSPIRE / ISO19115 Metadaten.
