### ISSUE TITLE
conformance specification title character

### ISSUE THREAD

**Issue by mhogeweg** [inspire-eu-validation/ets-repository#263]
in the conformance specification title there is use of various apostrophes, accents, etc. 

this article shows some different quotes (curly vs straight):
https://practicaltypography.com/straight-and-curly-quotes.html 

does the conformance test specifically test for exact matches? or can we assume single quotes (&apos;) will pass the test?

this is related to issue #262

**Comment by bilbomaticaue** [comment]
Dear @mhogeweg,

Thank you again for your comments.

The test admits the leading and trailing white-spaces from the sentence and the uppercase and lowercase letters. But the rest of the sentence must match, including apostrophes, accents, etc.

If you have any other question, please contact us.

Best regards.
