### ISSUE TITLE
Metadata ETS:  md-iso.c.3 : Dataset linkage constrainst are too restrictive

### ISSUE THREAD

**Issue by MarieLambois** [inspire-eu-validation/ets-repository#29]
Test on data linkage seems too restrictive  on 2 points:
·        XML document 'IGNF_BDTOPOr_2-2.xml', record 'IGNF_BDTOPOr_2-2.xml': The metadata record has a linkage property, but it references a resource at 'http://www.geoportail.fr/' that cannot be accessed. The HTTP status code when requesting the resource is: '301'. A status code of '200' is expected. -> 301 status code means a redirection so it should be considered as a valid page. 
·        XML document 'IGNF_BDTOPOr_2-2.xml', record 'IGNF_BDTOPOr_2-2.xml': The metadata record has a linkage property, which references a resource with media type 'text/html; charset=utf-8' at 'http://www.ign.fr/' which is not one of the media types indicating an INSPIRE network service. Please review the resource to check that it meets the linkage requirements; specifically, if the resource is a webpage, check that it provides further instructions or a client application that directly accesses the service. -> webpage are also welcomed so this should not be shown as an error, maybe just a warning or a manuel check

**Comment by cportele** [comment]
Yes on both: 
* Redirects should be ok for linkage elements that do not always go to an OGC Web Service. This should also be clarified in the ATS. I add a note in the test case.
* Yes, it should be flagged as a manual check, not an error.

**Comment by cportele** [comment]
Minor amendment: If the second message would have been the only message, the test would have been flagged as a manual check. It is the other message that results in the classification as an error. So, no change required to the ETS, the fix to the first part resolves the second part, too.

**Comment by cportele** [comment]
The tests have been updated. If there is still a problem, please reopen the issue. Thanks.
