### ISSUE TITLE
Metadata ETS : md-iso.c.3 Error in Status code detection

### ISSUE THREAD

**Issue by MarieLambois** [inspire-eu-validation/ets-repository#38]
The metadata record has a linkage property, but it references a resource at 'http://atom.geo-ide.developpement-durable.gouv.fr/atomMetadata/GetResourceDescription?id=c2f07613-7283-4d17-8e15-706fc0b8a406&scope=INTERNET' that cannot be accessed. The HTTP status code when requesting the resource is: 'text/xml;charset=ISO-8859-1'. A status code of '200' is expected.
 
 -> This is the mime-type of the response not the HTTP status code :
     
Request URL:
http://atom.geo-ide.developpement-durable.gouv.fr/atomMetadata/GetResourceDescription?id=c2f07613-7283-4d17-8e15-706fc0b8a406&scope=INTERNET
Request Method:
GET
Status Code:
200 OK

[md-gi-ns-edited+srs.zip](https://github.com/inspire-eu-validation/ets-repository/files/793463/md-gi-ns-edited.srs.zip)

**Comment by cportele** [comment]
Indeed, thanks. The distinction between the different cases was too weak and this led to an incorrect interpretation. This is now fixed.

However, I now get:

> XML document 'md-gi-ns-edited+srs.xml', record 'fr-120066022-jdd-5a90a78e-ef8e-456b-9c33-474d4ec63759': The metadata record has a linkage property, but it references a resource at 'http://atom.geo-ide.developpement-durable.gouv.fr/atomMetadata/GetResourceDescription?id=c2f07613-7283-4d17-8e15-706fc0b8a406&scope=INTERNET' that cannot be accessed. An exception occured when accessing the resource. Error message: "http://atom.geo-ide.developpement-durable.gouv.fr/atomMetadata/GetResourceDescription?id=c2f07613-7283-4d17-8e15-706fc0b8a406&scope=INTERNET": Invalid byte 2 of 3-byte UTF-8 sequence.

This might be because the media type in the response states that this is encoded in ISO-8859-1, but the XML states that UTL-8 is used. Or maybe it is in ISO-8859-1 which would conflict with the UTF-8 declaration. I will have a look.

> curl -i "http://atom.geo-ide.developpement-durable.gouv.fr/atomMetadata/GetResourceDescription?id=c2f07613-7283-4d17-8e15-706fc0b8a406&scope=INTERNET"
> ```
> HTTP/1.1 200 OK
> Date: Wed, 22 Feb 2017 13:38:02 GMT
> Server: Apache
> Content-Type: text/xml;charset=ISO-8859-1
> Vary: Accept-Encoding
> Transfer-Encoding: chunked
> 
> <?xml version="1.0" encoding="UTF-8"?>
> <feed xmlns="http://www.w3.org/2005/Atom" xmlns:georss="http://www.georss.org/georss" xmlns:gml="http://www.opengis.net/gml" xmlns:inspire_dls="http://inspire.ec.europa.eu/schemas/inspire_dls/1.0">
> ...
> ```

**Comment by cportele** [comment]
The (new) error is correct as the returned file is in ISO-8859-1, but the XML is processed as UTF-8 based on the charset statement.

In "Démarche" the "é" is one byte (E9) in the returned document. This is ISO-8859-1. In UTF-8, E9 is the start of the 3 byte sequence and the following byte 6D ("m") is not a valid second byte.

**Comment by MarieLambois** [comment]
Thanks for your quick correction. I will forward the new error to the developper of the ATOM feed.

**Comment by cportele** [comment]
Thanks. I will close the issue.
