### ISSUE TITLE
Different expressions reported for md-iso.c.3 in Conformance Class 'INSPIRE Profile based on EN ISO 19115 and EN ISO 19119'

### ISSUE THREAD

**Issue by thijsbrentjens** [inspire-eu-validation/ets-repository#52]
A Dutch organization pointed out that there seems to be different Expession reported in the same test "md-iso.c.3 dataset linkage" when the test is executed by:
1) Metadata for interoperability, sample report: http://35.157.17.37/etf-webapp/reports/245cb7c0-4f24-49ab-85fc-b4b1cdfc2b14 . This includes the Conformance class INSPIRE Profile based on EN ISO 19115 and EN ISO 19119

2) Conformance Class 'INSPIRE Profile based on EN ISO 19115 and EN ISO 19119' only.. , sample report: http://35.157.17.37/etf-webapp/reports/7fa1701a-3713-4906-846a-b6341df0d80d

The expression reported is different, while the assertion ID is the same (Assertion ID 	EIDbab97b1b-4ffe-4ac7-be22-16d10e3ed3dd)
The expression of 1) seems to be wrong.

**Comment by cportele** [comment]
There is a problem in the rendering of the test result in HTML. As a result only parts of the test result is shown in the report (in both cases).

**Comment by cportele** [comment]
The problem seem to be backslashes that are used in a URI. These are errors, but should be handled in the rendering of test result.

**Comment by jonherrmann** [comment]
Issue has been fixed in version 2.0.0 build 1703xx.  I can check the issue on the dev or dev7 machine on Monday.

**Comment by jonherrmann** [comment]
In version 2.0.0 build 170407 this error message for assertion EIDbab97b1b-4ffe-4ac7-be22-16d10e3ed3dd - "md-iso.c.3: Dataset linkage" is reported:

> The metadata record set has 1 record(s) with errors for this assertion.
> XML document 'nlps_nationaleparken.gml.xml', record 'dee67ed2-ace0-46ec-a81c-36cd29448940': The metadata record has a linkage property, but it references a resource at '\\lnv.intern\grp\RVO\GCC\Beheer\_Databeheer\_INSPIRE\Data\Beschermde gebieden\Geharmoniseerde INSPIRE data\Nationale_Parken\nlps_nationaleparken.gml' that is not an HTTP or HTTPS URL.

**Comment by cportele** [comment]
We will keep the issue open until the deployment used for testing has been updated to the new software version and we can verify in that version that the error has been fixed.

**Comment by cportele** [comment]
Check using http://inspire-sandbox.jrc.ec.europa.eu/etf-webapp/ and the behaviour with the backslashes was as expected. I am therefore closing the issue.
