### ISSUE TITLE
PS v3 codeList values check for GN NameStatus and Nativeness raises error

### ISSUE THREAD

**Issue by klimeto** [inspire-eu-validation/ets-repository#66]
I used the test suite Conformance class: Application schema, Protected Sites Simple and got following errors on Code List Values:

XML document 'PROTECTEDSITE_0173ED4B-61AB-483B-9B95-FC83BBBF4446_FIX.xml', ProtectedSite 'PROTECTEDSITE_0173ED4B-61AB-483B-9B95-FC83BBBF4446': The property 'nameStatus' has a value 'official' that is not one of the allowed values listed at http://inspire.ec.europa.eu/codelist/NameStatusValue.

Where 'official' is one of the allowed values: https://inspire.ec.europa.eu/codelist/NameStatusValue/official

The dataset has 1 feature(s) with errors for this assertion.
XML document 'PROTECTEDSITE_0173ED4B-61AB-483B-9B95-FC83BBBF4446_FIX.xml', ProtectedSite 'PROTECTEDSITE_0173ED4B-61AB-483B-9B95-FC83BBBF4446': The property 'nativeness' has a value 'endonym' that is not one of the allowed values listed at http://inspire.ec.europa.eu/codelist/NativenessValue.

Where 'endonym' is one of the allowed values: https://inspire.ec.europa.eu/codelist/NativenessValue/endonym

The data is encoded following example in Data Specification on Geographical Names as follows:
<gn:nativeness>endonym</gn:nativeness>
<gn:nameStatus>official</gn:nameStatus>

It also follows the definitions here: https://github.com/inspire-eu-validation/data/blob/3.0rc3/schemas/code-list-values.md#Nativeness3

Thanks,
Tomas

**Comment by cportele** [comment]
Thanks for reporting, your analysis is correct. The issue is that the INSPIRE registry silently changed from http to https - including a change in all identifiers. See issue #64. The test suites can now handle both http and https, but the versions with this change are not yet in the deployment at JRC.

**Comment by klimeto** [comment]
Yes it seems the issue with INSPIRE registry codeList values reference is fixed. All for assertions for PS Code list values in basic data types are passed.
Paste from the log:
31.08.2017 00:59:48 - "Test Case 'Code list values in basic data types' started"
31.08.2017 00:59:48 - "Test Assertion 'gmlas.e.1: GrammaticalNumber attributes': PASSED - 71 ms"
31.08.2017 00:59:48 - "Test Assertion 'gmlas.e.2: GrammaticalGender attributes': PASSED - 10 ms"
31.08.2017 00:59:48 - "Test Assertion 'gmlas.e.3: NameStatus attributes': PASSED - 5 ms"
31.08.2017 00:59:48 - "Test Assertion 'gmlas.e.4: Nativeness attributes': PASSED - 4 ms"
31.08.2017 00:59:48 - "Test Case 'Code list values in basic data types' finished: PASSED"
Thanks!
