### ISSUE TITLE
PS v3 Constraints check for <gn:pronunciation> raises void error 

### ISSUE THREAD

**Issue by klimeto** [inspire-eu-validation/ets-repository#67]
I have tested both examples from DS GN v3.1 for <gn:pronunciation> as follows:

```
<gn:pronunciation>
    <gn:PronunciationOfName>
          <gn:pronunciationIPA>[ˈdoːnaʊ]</gn:pronunciationIPA>
    </gn:PronunciationOfName>
</gn:pronunciation>
```

and 

```
<gn:pronunciation>
  <gn:PronunciationOfName/>
</gn:pronunciation>
```

they both raise error:

The constraint 'At least one of the two attributes pronunciationSoundLink and pronunciationIPA shall not be void, if the pronunciation property is provided.' is violated. 

For the second example it is correct, however why issues raises also for the first example where the pronIPA is provided?

Thanks,
Tomas

**Comment by cportele** [comment]
@klimeto: I tried it with the XML snippet that includes the pronunciationIPA element and I do not get this error. From looking at the Xpath expression in the test I also do not see immediately why it would raise an error. Is the file that you have used publicly available?

**Comment by klimeto** [comment]
I reran the test now again on [THIS ](https://drive.google.com/open?id=0B_LYIq94gSDiU3Y5eHNNZFVoaG8) file.
Here is the report: http://inspire-sandbox.jrc.ec.europa.eu/etf-webapp//v2/TestRuns/EIDadf634d6-e9d5-4d5c-ad34-88a300f518d0.html
raising the same error.

**Comment by cportele** [comment]
Thanks for the data! I see the issue now and have created a pull request (#68). This issue will be closed when the pull request is merged into the master branch. To fix the issue in the validator, it needs to be updated with the latest versions of the test suites.

Obviously this is the first time anyone had data where the pronunciation element was not nil...
