### ISSUE TITLE
Lineage validation fails with multilanguage metadata

### ISSUE THREAD

**Issue by mmarcosabate** [inspire-eu-validation/ets-repository#76]
Hi,
When validating a multilingual metadata I got an error informing that there are two lineage branches, when, in fact, there is only a lineage branch in two different languages.

I attach a metadata as an example,
[MultilingualMetadata.zip](https://github.com/inspire-eu-validation/ets-repository/files/1238121/MultilingualMetadata.zip)

Thanks in advance and best regards,
M. Marco

**Comment by cportele** [comment]
@mmarcosabate 
Yes, thanks for reporting this. Indeed it is an error in the test.

**Comment by mmarcosabate** [comment]
Dear Clemens,
Thanks for your quick response.All our metadata are multilingual. I would like to know if there is an estimated time to solve this bug, in order to be able to validate them properly.

Best regards,
Montse Marco


    El Lunes 21 de agosto de 2017 10:52, Clemens Portele <notifications@github.com> escribió:
 

 @mmarcosabate
Yes, thanks for reporting this. Indeed it is an error in the test.—

**Comment by cportele** [comment]
The issue is already fixed (via https://github.com/inspire-eu-validation/ets-repository/pull/77). The fix will be included in the INSPIRE validator when the service is updated to the latest version of the test suites.

cc: @michellutz
