### ISSUE TITLE
Incorrect Xpath in Pre-defined WFS assertion

### ISSUE THREAD

**Issue by cportele** [inspire-eu-validation/ets-repository#79]
Assertion "INSPIRE Unique Resource Identifier exists" (EID12b31278-5c35-4ddf-a583-11a02815b29b)

Current test (which will always return an empty node set): `//inspire_dls:ExtendedCapabilities/inspire_common:SpatialDataSet/inspire_common:UniqueResourceIdentifier`

Correct paths: 
both 
`//inspire_dls:ExtendedCapabilities/inspire_dls:SpatialDataSetIdentifier/inspire_common:Code` 
and
`//inspire_dls:ExtendedCapabilities/inspire_dls:SpatialDataSetIdentifier/inspire_common:Namespace`

**Comment by jonherrmann** [comment]
ETS: Capabilities -> Service Metadata -> Check ServiceMetadata in Capabilities
ATS: http://inspire.ec.europa.eu/id/ats/download-service/3.1/wfs-pre-defined/service-metadata
