### ISSUE TITLE
Wrong request sent to WFS

### ISSUE THREAD

**Issue by MarieLambois** [inspire-eu-validation/ets-repository#85]
When I test our WFS URL, it says that an Error 400 is returned. When we look at the log file we see that the request sent is : 
../inspire/wfs?service=WFS&VERSION=2.0.0
There is not the parameter request=GetCapabilities

If Y add this parameter in the original URL provided : 
../inspire/wfs?request=GetCapabilities
it works.

**Comment by cportele** [comment]
@MarieLambois Do you have a test report or the service URL (you can also send them by email, if you prefer) so that we can have a look what happens?

**Comment by MarieLambois** [comment]
I sent you the URL by email. I have no report it stops showing a red box in the corner.

**Comment by cportele** [comment]
Thanks - we will have a look and get back.

**Comment by jonherrmann** [comment]
If the service returns HTTP code 400 for a service URL without parameters, the validator will currently reject this URL. In this case you need to provide an URL with all parameters.

We opened an issue in the ETF repository but we will handle this as an 'nice-to-have' enhancement.

Ref https://github.com/interactive-instruments/etf-webapp/issues/128

**Comment by Sarah-f** [comment]
Hi,
what can I do if I use it with parameters and I get an http 400 error code? 
My service is secured (has credentials) and working. 
Thanks for any feedback!

**Comment by jonherrmann** [comment]
Hi, 

are you using the public JRC instance or do you have an internal deployment?

In the first case an URL to the report would help, in the second case we would need the etf.log file.

**Comment by Sarah-f** [comment]
I use the public one. but recognised that there isn't a report at all. Only a popup saying that "test object type could not be determined. Check your uploaded resource. Uploaded files may only composed of test data and no other data"
So it seems that validator doesn't start the tests...?

**Comment by jonherrmann** [comment]
Can you please post the complete URL to your service?

Even more helpful would be if you could mail me the credentials:
```
herrmann at interactive-instruments d ot de
```
I will treat the information confidentially.

**Comment by Sarah-f** [comment]
Hi, I will send my Url and credentials to your email. Thank you!

**Comment by jonherrmann** [comment]
The patch for this issue has been installed. See https://github.com/inspire-eu-validation/ets-repository/issues/118#issuecomment-341425213
